# Generated by Django 2.0.6 on 2019-03-07 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SuperHeroModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('fromWhere', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('power', models.CharField(max_length=100)),
                ('intention', models.CharField(max_length=100)),
                ('examples', models.TextField()),
            ],
        ),
    ]
